# Generated by Django 3.0.5 on 2020-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pace_of_losing_weight',
            field=models.IntegerField(default=3),
        ),
    ]
