# Generated by Django 3.0.5 on 2020-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200414_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, null=True),
        ),
    ]
